#+TITLE:     A Glossary of Hyperbolic Geometry
#+AUTHOR:    Phil Hazelden
#+EMAIL:     philip.hazelden@gmail.com
#+DATE:      %Y-%m-%d
#+DESCRIPTION:
#+KEYWORDS:
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:

#+LaTeX_HEADER:\usepackage[margin=1.2in]{geometry}
#+LaTeX_HEADER: \usepackage{amsmath}
#+LaTeX_HEADER: \usepackage{stmaryrd}
#+LaTeX_HEADER: \usepackage{hackgreek}
#+LaTeX_HEADER: \usepackage{suffix}
#+LaTeX_HEADER: \DeclareMathOperator{\tr}{Tr}
#+LaTeX_HEADER: \DeclareMathOperator{\ax}{Ax}
#+LaTeX_HEADER: \DeclareMathOperator{\aut}{Aut}
#+LaTeX_HEADER: \DeclareMathOperator{\isomp}{Isom^{+}}
#+LaTeX_HEADER: \newcommand{\dd}{\mathrm{d}}
#+LaTeX_HEADER: \newcommand{\chat}{\hat{ℂ}}
#+LaTeX_HEADER: \newcommand{\set}[1]{ \left\{ #1 \right\} }
#+LaTeX_HEADER: \newcommand{\ggl}[2]{\mathrm{GL}_{#1}\!\left(\mathbb{#2}\right)}
#+LaTeX_HEADER: \newcommand{\gsl}[2]{\mathrm{SL}_{#1}\!\left(\mathbb{#2}\right)}
#+LaTeX_HEADER: \newcommand{\psl}[2]{\mathrm{PSL}_{#1}\!\left(\mathbb{#2}\right)}
#+LaTeX_HEADER: \newcommand{\mat}[4]{\mat*{#1 & #2 \\ #3 & #4}}
#+LaTeX_HEADER: \WithSuffix{\newcommand}{\mat}*[1]{\left( \begin{smallmatrix} #1 \end{smallmatrix} \right)}
#+LaTeX_HEADER: \newcommand{\crossrat}[1]{[#1_1, #1_2, #1_3, #1_4]}

* Notation

- $\crossrat z$ :: The cross-ratio $\frac{z_1-z_2}{z_1-z_3}⋅\frac{z_4-z_3}{z_4-z_2}$, $z_i ∈ \chat$.
- $\aut(S)$ :: The group of conformal bijections $f:S → S$.
- $\ax(f)$ :: When $f ∈ \aut(ℙ)$ is hyperbolic, its axis $\ax(f)$ is the geodesic between its fixed points.
- $\chat$ :: The Riemann sphere $ℂ ∪ \set{∞}$.
- $C$ :: The Cayley transform $ℍ → 𝔻: C(z) = \frac{z-i}{z+i}$. A conformal isometry.
- $ℙ$ :: We use this when a statement applies to both $ℍ$ and $𝔻$.

* Definitions

- Accumulation point :: $x$ is an accumulation point of $S$ if every neighbourhood of $x$ intersects $S\smallsetminus\{x\}$. (We may have $x ∉ S$.)
- Circle :: On $\chat$, a "circle" might also be a straight line. Similarly, "concyclic" elements might be colinear.
- Conformal :: A conformal map $ℂ → ℂ$ is one which preserves angles.
- Discrete :: $G ≤ \gsl2R$ is discrete if it has no accumulation points in $\gsl2R$.
- Elementary :: A fuchsian group $G$ is elementary if it is cyclic generated by a parabolic, hyperbolic, or a finite-order elliptic; or $G = ⟨T, S | S^2 = 1, STS = T^{-1}⟩$ where $T$ is hyperbolic (and $S$ is necessarily elliptic).
- Free :: A group $G$ acts freely on $Ω$ if $g⋅x = x ⇒ g = 1$.
- Fuchsian group :: A discrete group of orientation preserving isometries of $ℍ$. Called /of the first kind/ if its limit set is $∂ℍ$, and /of the second kind/ otherwise.
- Fundamental domain :: $R ⊂ ℍ$ is a fundamental domain for a fuchsian group $G$ if all $g(R)$ are disjoint, and the $g(\overline{R})$ cover $ℍ$. We usually also assume that $\overline{R}$ is convex; $∂R ∩ ℍ$ is a countable union of geodesic segments, of which only finitely many meet any compact set in $ℍ$; and only finitely many $g(R)$ meet any compact set in $ℍ$.
- Isometry :: An isometry $f:M→M'$ is a bijection of metric spaces such that $d_M(x,y) = d_{M'}(f(x), f(y))$. It is /orientation preserving/ if $\det Df(x) > 0$ for all $x ∈ M$ ($Df$ is the Jacobian).
- Limit set :: The limit set of a fuchsian group $G$ is the closure (under the Euclidean topology on $∂ℍ$) of the set of non-elliptic fixed points of elements of $G$.
- Linear fractional transformation :: An LFT is a map $f : \chat → \chat$ of the form $f(z) = \frac{az+b}{cz+d}$ where $a,b,c,d ∈ ℂ$ and $ad-bc ≠ 0$. We say $f(∞) = a/c$, and $x/0 = ∞$. Let $t = \tr \mat abcd$. Then $f$ is called *parabolic* if $t = ±2$; *hyperbolic* if $t ∈ ℝ$ and $|t| > 2$; *elliptic* if $t ∈ ℝ$ and $|t| < 2$; and *loxodromic* if $t ∉ ℝ$.
- Properly discontinuous :: $G$ acts properly discontinously on $ℍ$ if for every compact $K ⊂ H$, $|\set{g ∈ G: g(K) ∩ K ≠ \varnothing}| < ∞$.
- Side :: If $R$ is a convex polygon and a fundamental domain for $G$, a side of $R$ is a maximal geodesic segment $S ⊂ ∂R$ of positive length, such that for some $g ∈ G$, $S ⊂ \overline{R} ∩ g(\overline{R})$. This $g$ is called the associated side pairing transformation.
- Topological group :: A group which is also a topological space, in which multiplication and inversion are continuous.

* Theorems

** Linear fractional transformations

- There is a surjective homomorphism $F: \ggl2C → \aut(\chat): \mat abcd → (z \mapsto \frac{az+b}{cz+d})$, with kernel $\set{λI : λ ∈ ℂ^×}$.
- Any LFT is a composition of
  - Translations :: $\mat 1t01: z \mapsto z+t$
  - Rotations :: $\mat*{e^{iθ} & -ae^{iθ} \\ 0 & 1}: z \mapsto e^{iθ}(z-a)+a$
  - Scaling :: $\mat {λ}001: z \mapsto λz$
  - Inversion :: $\mat 0110: z \mapsto 1/z$
- $\aut(\chat)$ acts transitively and freely on ordered triples of distinct points in $\chat$.
- The cross-ratio is invariant under $\aut(\chat)$: if $T ∈ \aut(\chat)$ then $\crossrat{z} = \crossrat{Tz}$.
- Distinct $z_1, …, z_4 ∈ \chat$ are concyclic iff $\crossrat z ∈ ℝ$.
- Corollary: $\aut(\chat)$ maps circles to circles.
- $\aut(𝔻)$ contains maps of the form $e^{iθ}\mat*{1 & -a \\ -\bar{a} & -1}$ where $a ∈ 𝔻$; or $\mat*{a & b \\ \bar{b} & \bar{a}}$ where $|a|^2 - |b|^2 = 1$.
- $\aut(ℍ)$ contains maps of the form $\mat abcd ∈ \ggl2R$ with positive determinant.

** Basics of hyperbolic Geometry

- On $𝔻$, we have the metric $\dd s^2 = \frac{4(\dd x^2 + \dd y^2)}{(1 - x^2 - y^2)^2}$.
- On $ℍ$, we have the metric $\dd s^2 = \frac{\dd x^2 + \dd y^2}{y^2}$.
- The Gauss curvature of both these metrics is $-1$.
- On $ℍ$, vertical lines are geodesics, and if $b ≥ a$ then $d_ℍ(ai, bi) = \ln(b/a)$. Other geodesics are arcs of circles with centres on $ℝ$.
- On $𝔻$, radial lines are geodesics, and $d_𝔻(0, z) = \ln(\frac{1+z}{1-z})$. Other geodesics are arcs of circles that cross $∂𝔻$ at right angles.
- $\isomp(ℙ)$ acts transitively on pairs of equidistant points in $ℙ$, and on cyclically ordered triples of points on $∂ℙ$.
- $\aut(ℙ) = \isomp(ℙ)$.
- Circles in $ℙ$ and $ℍ$ are circles in the Euclidian metric, but the centres in general do not agree.
- If a circle in $𝔻$ has Euclidean radius $ρ$, then it has hyperbolic radius $R = \ln(\frac{1+p}{1-p})$ and hyperbolic area $4π\sinh^2(R/2)$.
- If $P, P' ∈ ℙ$ and $Q, Q' ∈ ∂ℙ$ such that $Q-P-P'-Q'$ is a geodesic (with $Q$ adjacent to $P$ and $Q'$ adjacent to $P'$, then $d_ℙ(P, P') = \ln([Q, P', P, Q'])$.
- If $z_1, z_2 ∈ ℍ$, then $\cosh d_ℍ(z_1, z_2) = 1 + \frac{|z_1 - z_2|^2}{2\Im z_1 \Im z_2}$.
- If $z_1, z_2 ∈ 𝔻$, then $\tanh d_𝔻(z_1, z_2) = \frac{|z_1 - z_2|}{|1 - \bar{z_1}z_2|}$.
- Given a point $P$ and a line $L$, there is a unique perpendicular $K$ from $P$ to $L$, and this minimises $d(P,L)$. If $L'$ is a line through $P$ tangent to $L$ (sharing an endpoint) and $θ$ is the angle $KPL'$, then $\cosh d(P,L) = 1/\sin(θ)$.
- Given lines $L$ and $L'$ which do not meet even on $∂P$, there is a unique common perpendicular, and this minimises distance.
- Given a line $L$ and points $Y, Y'$, project perpendiculars to $X, X' ∈ L$. Then $d(Y, Y') > d(X, X')$ unless $Y, Y' ∈ L$.
- In $ℍ$, a curve $C$ equidistant from a line $L$ is an arc of a circle through the endpoints of $L$. If $L$ is a vertical, then $C$ is a ray with the same base as $L$.
- The angle sum of a hyperbolic $n$-gon is strictly less than $(n-2)π$.
- The area of a hyperbolic $n$-gon is $(n-2)π - (\text{angle sum})$.
- Triangle congruence tests: SSS, SAS, ASA and AAA all work.
- Given three angles summing to less than $π$, there is a triangle with those angles.
- Consider a triangle with sides length $a,b,c$ opposite angles $α, β, γ$ respectively.
  - Hyperbolic pythagorean theorem: if $γ = π/2$, then $\cosh c = \cosh a \cosh b$. Further, $a + b ≤ c + \cosh^{-1}(2)$.
  - Hyperbolic trigonometry: $\sin β = \frac{\sinh b}{\sinh c}$, $\cos α = \frac{\tanh a}{\tanh c}$.
  - Sinh rule: $\frac{\sinh a}{\sin α} = \frac{\sinh b}{\sin β} = \frac{\sinh c}{\sin γ}$.
  - Cosh rule 1: $\cos γ = \frac{\cosh a \cosh b - \cosh c}{\sinh a \sinh b}$.
  - Cosh rule 2: $\cosh c = \frac{\cos α \cos β + \cos γ}{\sin α \sin β}$.

** Isometries of $𝔻$ and $ℍ$

- If $f ∈ \aut(ℙ)$ is palindromic, it has one fixed point $z_0$ on $∂ℙ$. It maps horocycles (circles tangent to $ℝ$ at $z_0$) onto themselves; and maps geodesics with an endpoint at $z_0$ onto each other. In $ℍ$, if $z_0 = ∞$, $f$ is a translation $z \mapsto z + β$ for some $β ∈ ℝ$.
- If $f ∈ \aut(ℙ)$ is hyperbolic, it has two fixed points on $∂ℙ$, $z_-$ (repelling) and $z_+$ (attracting). It maps lines equidistant from $\ax(f)$ onto themselves.
- If $f ∈ \aut(ℙ)$ is elliptic, it has one fixed point $z_0$ in $ℙ$. It maps circles centred on $z_0$ onto themselves.
- A hyperbolic isometry $f$ is conjugate to some $T ∈ \aut(ℍ): T(z) = λz$, with fixed points $0$ and $∞$. $λ$ is called the multiplier of $f$. For $x ∈ \ax(f)$, we have $d(x, T(x)) = \ln λ =: l$. For general $z ∈ ℙ$, $\sinh \frac{d(z, T(z))}{2} = \sinh \frac{l}{2} \cosh \frac{d(z, \ax(f))}{2}$.
- If $L$ is any geodesic, there is a unique orientation-reversing isometry $σ$ such that $σ^2 = 1$, $σ|_L = 1$, and $d(x, L) = d(σ(x), L)$.
- Any $f ∈ \aut(ℙ)$ can be written as a product of two such reflections. It is hyperbolic if the lines don't intersect, parabolic if they intersect on $∂ℙ$, and elliptic if they intersect in $ℙ$.
- Any nonabelian subgroup of $\aut(ℙ)$ contains hyperbolic elements.


** Groups of orientation-preserving isometries

- $\gsl2R$ and $\psl2R$ are topological groups.
- If $G ≤ \gsl2R$, TFAE:
  - $G$ has no accumulation points in $G$.
  - $G$ has no accumulation points in $\gsl2R$.
  - $\mat 1001$ is an isolated point in $G$.
- If $G ≤ \gsl2R$, TFAE:
  - $G$ does not act properly discontinously on $ℍ$.
  - Some $G$-orbit in $ℍ$ has accumulation points in $ℍ$.
  - All $G$-orbits in $ℍ$ have accumulation points in $ℍ$, with the possible exception of one point fixed by all $g ∈ G$.
- If $G$ acts properly discontinuously on $ℍ$, $G$ is discrete.
- If $G < \aut(ℙ)$ is abelian and discrete, and $T ∈ G$ is either elliptic or parabolic, then $G = ⟨T⟩$ is cyclic.
- Any discrete subgroup of $\aut(ℙ)$ is cyclic.
- If $K ⊂ ℍ$ is compact, then $E = \set{T ∈ \aut(ℍ) : T(i) ∈ K}$ is compact in $\aut(ℍ)$.
- If $G$ is discrete, it acts properly discontinously on $ℍ$.
- If $G$ is discrete and infinite, then every orbit has accumulation points on $∂ℍ$.
- $G$ fuchsian, $h, g ∈ G$ with $h$ hyperbolic. Then either $g$ is hyperbolic with the same fixed points as $h$, or no fixed point of $h$ is also a fixed point of $g$.
- If $g, h ∈ \aut(ℍ)$, $g$ elliptic or parabolic, with no fixed points shared. Then $ghg^{-1}h^{-1}$ is hyperbolic.
- $G$ fuchsian, $h,g ∈ G$ with $h$ hyperbolic and $g(\ax(h)) ≠ \ax(h)$. Then $G$ contains infinitely many hyperbolic elements, all with distinct axes.
- $G$ fuchsian. TFAE:
  - $G$ elementary.
  - There is $H ≤ G$ abelian with $[G:H]$ finite.
  - There is a finite $G$-orbit in $\overline{ℍ}$.
- If $G$ is fuchsian, $\mat 1101 ∈ G$ and $\mat abcd ∈ G$, then either $c = 0$ or $|c| ≥ 1$.
- *Jørgensen's inequality* If $A,B$ in a non-elementary fuchsian group, then $|\tr^2(A) - 4| + |\tr(ABA^{-1}B^{-1}) - 2| ≥ 1$.

** Fundamental domains, side pairings and the cycle condition

- We can construct a fundamental domain for any fuchsian group $G$ as follows: choose any $z_0 ∈ ℍ$ which is not fixed by any $G$. For $g ∈ G$, define $H_g(z_0) = \set{ z ∈ ℍ: d(z, z_0) < d(z, g(z_0)) }$. Then $R(z_0) = \bigcap_{g ∈ G\setminus\set{1}}H_g(z_0)$ is a fundamental domain, satisfying the extra assumptions.
- Let $G$ be fuchsian, $R$ a fundamental convex polygon, and $G_0 < G$ a collection of side pairings which together pair all the sides of $R$. Then $G_0$ is a set of generators for $G$.
- Choose a vertex $v_0$ of a fundamental polygon $R$. Draw a small path around $v$, and label the regions that it meets clockwise by $R = h_0R, h_1R, … h_{k-1}R, h_kR = R$. Then each $h_i^{-1}h_{i+1}$ is a side pairing, so $\prod{i=0}^{k-1}(h_i^{-1}h_{i+1}) = 1$ gives a relation of side pairings. If we do this for all vertices, the relations we get together with the generators $G_0$ form a presentation for $G$.
- Let $g_i$ be the side pairing of the side preceding $v_i$ clockwise, and $v_{i+1} = g_i(v_i)$. This gives us a relation $(g_{k-1}…g_1g_0)^p = 1$ for some $p$.
- If $R$ has a single vertex in $∂ℍ$, then $g_{k-1}…g_0$ is parabolic.
- If $R$ has two vertices in $∂ℍ$, then either $g_{k-1}…g_0$ is hyperbolic or $G$ is elementary.
- *Poincaré* Let $R ⊂ ℍ$ be a finite sided convex polygon, with sides paired by $g_1,…,g_k$. Suppose that for each cycle associated to an interior vertex, the angle sum is $2π/p$ for some $p ∈ ℕ$, and for any ideal vertex the associated cycle product is parabolic. Then $G = ⟨g_1,…,g_k⟩$ is fuchsian, $R$ is a fundamental domain, and the cycle relations give a presentation for $G$.
- If $G$ is fuchsian and non-elementary, it has a subgroup isomorphic to the free group on two elements.

** Limit sets

- If $G$ is fuchsian with limit set $Λ$, then
  - $Λ$ is closed and $G$-invariant.
  - $|Λ| ≤ 2$ iff $G$ is elementary. Otherwise $|Λ| = ∞$.
  - Every $G$-orbit is dense in $Λ$ (i.e.\nbsp{}$Λ$ is minimal in the sense that it has no proper closed $G$-invariant subsets).
  - If $G$ is non-elementary, then $Λ$ is uncountable, closed and has no isolated points.
  - If $G$ is of the second kind, $Λ$ is nowhere dense in $∂𝔻$.
  - For any $x ∈ \overline{𝔻}$, $Λ$ is the set of accumulation points of $G⋅x$.
- Corollary: if $G$ is of the second kind, its limit set is homeomorphic to the Cantor set.
